gasoline/models/document.py
# -*- coding: utf-8 -*-

from datetime import datetime
import markdown2
import mediawiki
from mongoengine.fields import GridFSProxy
from bson.objectid import ObjectId

# from gasoline.core.utils import genid
from gasoline.core.extensions import db
from gasoline.core.signals import event, activity
from gasoline.core.diff import Diff
from gasoline.services.acl import ACE
from .comment import Comment
from .user import User, json_schema_resource as json_schema_user
from .attachment import (
    Attachment, json_schema_resource as json_schema_attachment)

rest_uri_collection = '/api/v1/documents/<space>'
rest_uri_resource = '{}/<doc_id>'.format(rest_uri_collection)

json_schema_resource = {
    'title': 'Document resource Schema',
    'type': 'object',
    'required': ['space', 'title', 'author'],
    'properties': {
        '_id': {'type': 'string'},
        'title': {'type': 'string'},
        'space': {'type': 'string'},
        'content': {'type': 'string'},
        'tags': {
            'type': 'array',
            'items': {
                'title': 'Tag schema',
                'type': 'string'
            },
        },
        'attachments': {
            'type': 'array',
            'items': json_schema_attachment,
        },
        'creation': {'type': 'string'},
        'last_update': {'type': 'string'},
        'author': json_schema_user,
        'last_author': json_schema_user,
        'current_revision': {'type': 'integer'},
        'uri': {'type': 'string'},
    },
}

json_schema_collection = {
    'title': 'Documents collection Schema',
    'type': 'array',
    'minItems': 1,
    'items': json_schema_resource,
}


class DocumentRevision(db.EmbeddedDocument):
    number = db.IntField(primary_key=True, default=1)
    title_diff = db.StringField(default=None)
    space_diff = db.StringField(default=None)
    content_diff = db.StringField(default=None)
    date = db.DateTimeField()
    author = db.ReferenceField(User)

    def __repr__(self):
        return '<DocumentVersion number=%r>' % self.number


class BaseDocumentQuerySet(db.QuerySet):

    def get_document(self, doc):
        if ObjectId.is_valid(doc):
            return self.filter(id=doc)
        else:
            return self.filter(title=doc)


class BaseDocument(db.DynamicDocument):
    _title = db.StringField(db_field='title', unique_with='_space')
    _space = db.StringField(db_field='space', default=u'main')
    _content = db.StringField(db_field='content')
    tags = db.ListField(db.StringField())
    attachments = db.ListField(db.EmbeddedDocumentField(Attachment))

    acl = db.SortedListField(db.EmbeddedDocumentField(ACE),
                             ordering='predicate')

    # document Metadata
    creation = db.DateTimeField(default=datetime.utcnow)
    last_update = db.DateTimeField(default=datetime.utcnow)
    author = db.ReferenceField(User, required=True)
    last_author = db.ReferenceField(User)
    current_revision = db.IntField(default=1)
    markup = db.StringField(default=u'xhtml')

    meta = {
        'indexes': ['title', 'space'],
        'ordering': ['title', 'space'],
        'queryset_class': BaseDocumentQuerySet,
    }

    _history = None
    _next_revision = None
    _diff = None

    def _get_history(self):
        # get history document or create it
        if self._history is None:
            self._history = DocumentHistory.objects(document=self.id)
            if len(self._history) == 0:
                history = DocumentHistory(document=self)
                history.save()
                self._history = DocumentHistory.objects(document=self)

    def _get_next_revision(self):
        # create new revision if not exist
        if self._next_revision is None:
            self._next_revision = DocumentRevision()
            self._next_revision.date = self.last_update
            self._next_revision.number = self.current_revision
            self._next_revision.author = self.last_author

    def _get_diff(self):
        # get diff object
        if self._diff is None:
            self._diff = Diff()

    @property
    def uri(self):
        return rest_uri_resource.\
            replace("<space>", self.space).\
            replace("<doc_id>", unicode(self.id))

    @property
    def title(self):
        return self._title

    @title.setter
    def title(self, title):
        if self._title is not None:
            self._get_next_revision()
            self._get_diff()

            # compute title diff
            title_patches = self._diff.patch_make(title, self.title)
            if len(title_patches) > 0:
                self._next_revision.\
                    title_diff = self._diff.patch_toText(title_patches)
        self._title = title

    @property
    def space(self):
        return self._space

    @space.setter
    def space(self, space):
        if self._space is not None:
            self._get_next_revision()
            self._get_diff()

            # compute space diff
            space_patches = self._diff.patch_make(space, self.space)
            if len(space_patches) > 0:
                self._next_revision.\
                    space_diff = self._diff.patch_toText(space_patches)
        self._space = space

    @property
    def content_html(self):
        if self.markup == 'xhtml':
            return self.content
        elif self.markup == 'mediawiki':
            return mediawiki.wiki2html(self.content, True)
        else:
            return markdown2.markdown(self.content)

    @property
    def content(self):
        # return self._content
        if self.markup == 'xhtml':
            return self._content
        elif self.markup == 'mediawiki':
            return mediawiki.wiki2html(self._content, True)
        else:
            return markdown2.markdown(self._content)

    @content.setter
    def content(self, content):
        if self._content is not None:
            self._get_next_revision()
            self._get_diff()

            # compute content diff
            content_patches = self._diff.patch_make(content, self.content)
            if len(content_patches) > 0:
                self._next_revision.\
                    content_diff = self._diff.patch_toText(content_patches)
        self._content = content

    def get_revision(self, revision_number):
        self._get_diff()
        self._get_history()
        history = self._history.first()
        # patch content for each revisions
        for revision in reversed(history.revisions):
            # break if requested revision
            if revision.number < revision_number:
                break
            # apply title patch
            if revision.title_diff is not None:
                title_patches = self._diff.\
                    patch_fromText(revision.title_diff)
                self._title = self._diff.\
                    patch_apply(title_patches, self.title)[0]
            # apply space patch
            if revision.space_diff is not None:
                space_patches = self._diff.\
                    patch_fromText(revision.space_diff)
                self._space = self._diff.\
                    patch_apply(space_patches, self.space)[0]
            # apply content patch
            if revision.content_diff is not None:
                content_patches = self._diff.\
                    patch_fromText(revision.content_diff)
                self._content = self._diff.\
                    patch_apply(content_patches, self.content)[0]
            self.current_revision = revision.number
            self.last_update = revision.date

    def get_acl(self, predicate=None):
        """get acl for predicate"""
        if predicate is not None:
            acl = [a for a in self.acl if a.predicate == predicate]
        else:
            acl = self.acl

        return acl

    def add_ace(self, ace):
        """add ace"""
        if len(self.get_acl(ace.predicate)) == 0:
            self.update(push__acl=ace)
        else:
            raise BaseException

    def update_ace(self, ace):
        """update ace"""
        if len([a for a in self.acl if a.predicate == ace.predicate]) < 1:
            raise BaseException
        for old_ace in self.get_acl(ace.predicate):
            self.delete_ace(old_ace)
        self.reload()
        self.add_ace(ace)

    def delete_ace(self, ace):
        """remove ace"""
        if ace in self.acl:
            self.update(pull__acl=ace)
        else:
            raise BaseException

    @property
    def comments(self):
        return Comment.objects().all()

    def get_comment(self, comment_id):
        return Comment.objects(doc=self, id=comment_id).first()

    def get_comments(self):
        return Comment.objects(doc=self).all()

    def add_comment(self, comment):
        comment.doc = self
        comment.save()

        # # send activity event
        # activity.send(verb='add', object=self, object_type='comment')

    def update_comment(self, comment):
        comment.doc = self
        comment.save()

        # # send activity event
        # activity.send(verb='edit', object=self, object_type='comment')

    def delete_comment(self, comment):
        comment.delete()

        # # send activity event
        # activity.send(verb='delete', object=self, object_type='comment')

    def get_attachment(self, filename):
        """get attached file"""
        # get attachment if exist
        for idx, attachment in enumerate(self.attachments):
            if filename == attachment.filename:
                return attachment.attachment
        # if filename in self.attachments:
        #     print filename
        raise BaseException

    def add_attachment(self, file, filename, content_type, user):
        """attach file to document"""
        # update file if already exists
        for idx, attachment in enumerate(self.attachments):
            if filename == attachment.filename:
                # update file in gridfs

gasoline/forms/login.py
# -*- coding: utf-8 -*-

from flask.ext.babel import lazy_gettext as _l
from flask.ext.wtf import Form
from wtforms import TextField, BooleanField, PasswordField
from wtforms.validators import Required

from gasoline.models import User


class LoginForm(Form):
    name = TextField(_l(u'Username'),
                     description=_l(u'Username'), validators=[Required()])
    password = PasswordField(_l(u'Password'),
                             description=_l(u'Password'),
                             validators=[Required()])
    remember_me = BooleanField(_l(u'Remember me'),
                               description=_l(u'Remember me'), default=False)

    def validate(self):
        if not Form.validate(self):
            return False
        user = User.objects(name=self.name.data).first()
        if user is None:
            self.name.errors.append(_l(u'Username or password mismatch.'))
            return False
        return True

gasoline/user/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, flash, redirect, session
from flask import url_for, request
from flask.ext.babel import gettext as _, ngettext as n_
from flask.ext.login import login_user, logout_user
from flask.ext.login import current_user, login_required

from .models import User
from .forms import LoginForm

user = Blueprint('user',
                 __name__,
                 url_prefix='/user',
                 template_folder='templates')

route = user.route


@route('/login', methods=['GET', 'POST'])
def login():
    if current_user is not None and current_user.is_authenticated():
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(name=form.name.data).first()
        if user.check_password(form.password.data):
            session['remember_me'] = form.remember_me.data
            login_user(user, remember=session['remember_me'])
            flash(_('Logged in successfully.'), 'success')
            return redirect(request.args.get("next") or
                            url_for("frontend.index"))

        flash(_('Logging failed.'), 'danger')
        return redirect(url_for('.login'))
    return render_template('login.html',
                           title='Sign In',
                           form=form)


@route('/logout')
def logout():
    logout_user()
    return redirect(url_for('frontend.index'))


@route('/profile/<name>', methods=['GET', 'POST'])
@login_required
def profile(name):
    user = User.objects(name=name).first()
    if user is None:
        flash(n_('User %(name) not found.', name), 'danger')
        return redirect(url_for('frontend.index'))
    return render_template('profile.html', **locals())

gasoline/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{{ page_title|default(_('Project')) }}{% endblock %} - Gasoline</title>
    {% assets "css" %}<link href="{{ ASSET_URL }}" rel="stylesheet" media="screen">{% endassets %}
    <meta name="description" content="Gasoline, collaborative wiki">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    {% block topbar %}
    <nav class="navbar navbar-default" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">{{ _('Toggle navigation') }}</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Gasoline</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <form action="{{ url_for('document.edit', space=space | default('main')) }}">
            <button class="btn btn-default navbar-btn">{{ _('Create') }}</button>
            </form>
          </li>
      {% if current_user.is_authenticated() %}
          <li>
            <form class="navbar-form navbar-left form-inline" role="search" action="{{url_for('search.search')}}" method="get" name="search">
              <div class="form-group has-feedback dropdown" id="search_input">
                {{ g.search_form.query(class='form-control', style='width: 180px', autocomplete='off', placeholder=g.search_form.query.description)|safe }}
                <i id="search_button" class="fa fa-search fa-fw form-control-feedback"></i>
                <ul id="search_results" class="dropdown-menu"></ul>
              </div><!-- /input-group -->
            </form>
          </li>
      {% endif %}
        </ul>
      {% if current_user.is_authenticated() %}
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-lg"></i> <i class="fa fa-caret-down"></i></a>
          <ul class="dropdown-menu">
            <li{% if request.path.startswith("/user") %} class="active"{% endif %}>
              <a href="{{ url_for('user.profile', name=current_user.name) }}"><i class="fa fa-user"></i> {{ _('My account') }}</a>
            </li>
            <li class="divider"></li>
            <li><a href="{{ url_for('user.logout') }}"><i class="fa fa-sign-out"></i> {{ _('Logout') }}</a></li>
          </ul>
        </li>
      </ul>
      {% endif %}
      </div><!-- /.navbar-collapse -->
    </nav>
    {% endblock %}

  <div class="content">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{ category }} alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <i class="fa {% if category == 'success' %}fa-check{% elif category == 'danger' %}fa-warning{% elif category == 'info' %}fa-info-circle{% endif %}"></i> {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>
    {% assets "js" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
    {% assets "js-fr" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
    {% block js %}{% endblock %}
  </body>
</html>

gasoline/templates/dashboard.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <h3>{{ _('Documents:') }}</h3>
        <ul>
        {% for doc in docs %}
        	<li><a href="{{ url_for('document.view', space=space, doc_id=doc.id) }}">{{ doc.title }}</a><br /><small><time datetime="{{ doc.last_update }}Z">{{ doc.last_update | date }}</time> by Someone</small></li>
        {% endfor %}
        </ul>
    </div>
    <div class="col-md-6">
        <div class="activity-stream">
            <h3>{{ _('Activity Stream:') }}</h3>
            {% for event in activity %}
            <div>
                <div class="pull-left"><i class="{{ event.icon }} fa-fw"></i></div>
                <p>
                    <a href="{{ url_for('user.profile', name=event.actor.name) }}">{{ event.actor.name }}</a> {{ event.action }}  <a href="{{ event.object.url }}">{{ event.object.display_name }}</a><br />
                    <small><time class="timeago" datetime="{{ event.published }}Z" data-toggle="tooltip" data-placement="bottom">{{ event.published | datetime }}</time></small>
                </p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

gasoline/templates/document.html
{%- extends "base.html" -%}
{% block content -%}
{% if doc.id %}<div class="pull-right btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-cog"></i> {{ _('Tools') }} <i class="fa fa-caret-down"></i>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ url_for('document.edit', space=space, doc_id=doc.id) }}">{{ _('Edit') }}</a></li>
        <li><a href="{{ url_for('document.history', space=space, doc_id=doc.id) }}">{{ _('History') }}</a></li>
        <li><a href="{{ url_for('document.attachments', space=space, doc_id=doc.id) }}">{{ _('Attachments') }} ({{ doc.attachments|length }})</a></li>
        <li><a href="#">{{ _('Rights') }}</a></li>
        <li class="divider"></li>
        <li><a href="#">{{ _('Links') }}</a></li>
        <li><a href="#">{{ _('Informations') }}</a></li>
    </ul>
</div>
{% if request.endpoint != 'document.view' %}
<div class="pull-right">
<a href="{{ url_for('document.view', space=space, doc_id=doc.id) }}" class="btn btn-default">
    <i class="fa fa-reply"></i> {{ _('View Document') }}
</a>&nbsp;
</div>
{% endif %}
{% endif %}
<div>Breadcrumb</div>
<div>
{% block document_header %}{% endblock document_header %}
{% block document_content %}{% endblock document_content %}
{% block document_footer %}{% endblock document_footer %}
</div>
{%- endblock content %}

gasoline/templates/document_attachments.html
{%- extends "document.html" -%}
{%- block document_header -%}
<div class="page-header">
<h1>{{ _('Attachments') }}</h1>
</div>
{%- endblock document_header %}

{%- block document_content -%}
{% if doc.attachments|length < 1 %}
<div>{{ _('There are currently no attachments on this document.') }}</div>
{% else %}
<ul>
{% for file in doc.attachments %}
    <li><a href="{{ url_for('document.attachment', space=space, doc_id=doc.id, filename=file.filename) }}">{{ file.filename }}</a> - {{ file.size }}<a href="{{ url_for('document.delete_attachment', space=space, doc_id=doc.id, filename=file.filename) }}"><i class="pull-right fa fa-trash-o"></i></a></li>
{% endfor %}
</ul>
{%- endif %}
<form method="POST" enctype="multipart/form-data" action="{{ url_for('document.upload', space=space, doc_id=doc.id) }}">
    <input type="file" name="upload">
    <button type="submit" class="btn btn-default">{{ _('Upload') }}</button>
</form>
{%- endblock document_content %}

gasoline/templates/document_edit.html
{%- extends "document.html" -%}
{% block document_content -%}
{% from "macros.html" import render_bootstrap_field %}
<div class="page-header">
</div>
<form class="form-horizontal" role="form" action="" method="post" name="edit_document">
	{{form.hidden_tag()}}
	{% if form.csrf_token.errors %}
		{% for error in form.csrf_token.errors %}
    		<div class="alert alert-danger">{{ error }}</div>
		{% endfor %}
	{% endif %}

	{{ render_bootstrap_field(form.title) }}
	<div class="form-group{% if form.content.errors %} error{% endif %}">
	    <label class="col-sm-2 control-label" 
	        for="{{ form.content.id }}">
	        {{ form.content.label }}
	    </label>
	    <div class="col-sm-8 controls">
	        {{ form.content(class="form-control", rows="20") }}
	        {% if form.content.errors -%}
	            {% for error in form.content.errors -%}
	            <span class="help-block error">{{ error }}</span>
	            {%- endfor %}
	        {%- endif %}
	    </div>
	</div>

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-4">
		<button type="submit" class="btn btn-default">{{ _('Submit') }}</button>
	</div>
	</div>
</form>
{%- endblock document_content %}

gasoline/templates/document_history.html
{%- extends "document.html" -%}
{%- block document_header %}
<div class="page-header">
<h1>{{ _('History') }}</h1>
</div>
{%- endblock document_header %}

{%- block document_content -%}
<table class="table table-hover">
    <thead>
    <tr>
        <th>{{ _('Version') }}</th>
        <th>{{ _('Date') }}</th>
        <th>{{ _('Author') }}</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td><a href="{{ url_for('document.view', space=space, doc_id=doc.id) }}">{{ _('CURRENT') }}</a> (v. {{ doc.current_revision }})</td>
        <td><time datetime="{{ doc.last_update }}Z">{{ doc.last_update | datetime }}</time></td>
        <td><a href="{{ url_for('user.profile', name=doc.last_author.id) }}">{{ doc.last_author.display_name }}</a></td>
    </tr>
    {% for revision in history.reverse_revisions -%}
    <tr>
        <td><a href="{{ url_for('document.revision', space=space, doc_id=doc.id, revision=revision.number) }}">v. {{ revision.number }}</a></td>
        <td><time datetime="{{ revision.date }}Z">{{ revision.date | datetime }}</time></td>
        <td><a href="{{ url_for('user.profile', name=revision.author.id) }}">{{ revision.author.display_name }}</a></td>
    </tr>
    {%- endfor %}
    </tbody>
</table>
{%- endblock document_content %}

gasoline/templates/document_view.html
{%- extends "document.html" -%}
{%- block document_header -%}
<div class="page-header">
<h1><a href="{{ url_for('document.view', space=space, doc_id=doc.id) }}">{{ doc.title }}</a></h1>
<small>{{ _('Created') }} <time class="timeago" datetime="{{ doc.creation }}Z" data-toggle="tooltip" data-placement="bottom">{{ doc.creation | datetime }}</time>, {{ _('last update') }} <time class="timeago" datetime="{{ doc.last_update }}Z" data-toggle="tooltip" data-placement="bottom">{{ doc.last_update | datetime }}</time> (v.{{ doc.current_revision }})</small>
</div>

{% if request.endpoint != 'document.view' %}
<div class="alert alert-warning"><i class="fa fa-warning fa-lg"></i> {{ _('Old version. View') }} <a href="{{ url_for('document.view', space=space, doc_id=doc.id) }}">{{ _('current version') }}</a>.</div>
{% endif %}
{%- endblock document_header %}

{%- block document_content -%}
<div>{{ doc.content_html|safe }}</div>
{%- endblock document_content %}

{%- block document_footer -%}
<div id="document-tag-list" class="tag-list"></div>

<ul class="nav nav-tabs">
  <li class="active"><a href="#comments" data-toggle="tab">{{ _('Comments') }}</a></li>
</ul>

<div class="tab-content">
    <div class="tab-pane active" id="comments">
        {%- for comment in doc.comments recursive -%}
        <blockquote>
          <footer><a href="{{ url_for('user.profile', name=comment.author.id) }}">{{ comment.author.id }}</a> <time class="timeago" datetime="{{ comment.date }}Z" data-toggle="tooltip" data-placement="bottom">{{ comment.date | datetime }}</time></footer>
          <p>{{ comment.content }}</p>
        </blockquote>
            {%- if comment.reply -%}
                <ul>{{ loop(comment.reply) }}</ul>
            {%- endif -%}
        {%- endfor -%}
        {% from "macros.html" import render_bootstrap_field %}
        <form class="form-horizontal" role="form" action="" method="post" name="login">
            {{comment_form.hidden_tag()}}
            {% if comment_form.csrf_token.errors %}
                {% for error in comment_form.csrf_token.errors %}
                    <div class="alert alert-danger">{{ error }}</div>
                {% endfor %}
            {% endif %}
            {{ render_bootstrap_field(comment_form.content) }}
            <div class="form-group">
            <div class="col-sm-offset-2 col-sm-4">
                <button type="submit" class="btn btn-default">{{ _('Comment') }}</button>
            </div>
            </div>
        </form>
    </div>
</div>
{%- endblock document_footer %}
{%- block js -%}
<script>
    $(function() {
        $('#document-tag-list').tags({
            tagData: {{doc.tags|tojson|safe}},
            beforeAddingTag: function(tag){ returncode = true; 
                $.ajax({
                    type: "GET",
                    url: "/document/{{ space }}/add/tag/{{ doc_id }}/"+tag,
                    cache: false,
                    async: false,
                    success: function(data) {
                        returncode = true;
                    },
                    error: function(data) {
                        returncode = false;
                    }
                });
                return returncode;
            },
            beforeDeletingTag: function(tag){ returncode = true; 
                $.ajax({
                    type: "GET",
                    url: "/document/{{ space }}/remove/tag/{{ doc_id }}/"+tag,
                    cache: false,
                    async: false,
                    success: function(data) {
                        returncode = true;
                    },
                    error: function(data) {
                        returncode = false;
                    }
                });
                return returncode;
            }
        });
    });
</script>
{%- endblock -%}

gasoline/templates/edit_document.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
{% from "macros.html" import render_bootstrap_field %}
<form class="form-horizontal" role="form" action="" method="post" name="edit_document">
	{{form.hidden_tag()}}
	{% if form.csrf_token.errors %}
		{% for error in form.csrf_token.errors %}
    		<div class="alert alert-danger">{{ error }}</div>
		{% endfor %}
	{% endif %}

	{{ render_bootstrap_field(form.title) }}
	<div class="form-group{% if form.content.errors %} error{% endif %}">
	    <label class="col-sm-2 control-label" 
	        for="{{ form.content.id }}">
	        {{ form.content.label }}
	    </label>
	    <div class="col-sm-8 controls">
	        {{ form.content(class="form-control", rows="20") }}
	        {% if form.content.errors -%}
	            {% for error in form.content.errors -%}
	            <span class="help-block error">{{ error }}</span>
	            {%- endfor %}
	        {%- endif %}
	    </div>
	</div>

	<div class="form-group">
	<div class="col-sm-offset-2 col-sm-4">
		<button type="submit" class="btn btn-default">{{ _('Submit') }}</button>
	</div>
	</div>
</form>
{% endblock %}

gasoline/templates/index.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
<h1>Hi !</h1>

<ul>
{% for doc in docs %}
	<li><a href="{{ url_for('dashboard.view', doc_id=doc.id) }}">{{ doc.title }}</a> ({{ doc.status }})</li>
{% endfor %}
</ul>
{% endblock %}

gasoline/templates/index.html.jinja2
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{{ page_title|default(_('Project')) }}{% endblock %} - Gasoline</title>
    {% assets "css" %}<link href="{{ ASSET_URL }}" rel="stylesheet" media="screen">{% endassets %}
    <meta name="description" content="Gasoline, collaborative wiki">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    <div id="header-region"></div>
    <div class="container">
      <div id="main-region"></div>
    </div>
    <div id="footer-region"></div>
    <div id="dialog-region" tabindex="-1" role="dialog" aria-labelledby="Dialog" aria-hidden="true"></div>

    {% assets "js" %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
    {% assets "js-"+g.locale.language %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}
    {% assets "jst-"+g.locale.language %}<script type="text/javascript" src="{{ ASSET_URL }}"></script>{% endassets %}

    <script type="text/javascript">
        $(function() {
          Gasoline.currentUser = new Gasoline.Entities.User({ 
            name: "{{ current_user.name }}",
            display_name: "{{ current_user.display_name }}",
            id: "{{ current_user.name }}",
          });

          Gasoline.start();
        });
      </script>
  </body>
</html>

gasoline/templates/search_results.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
<h4>{{ ngettext('%(count)d of %(num)i result found in %(seconds)fs', '%(count)d of %(num)i results found in %(seconds)fs', results['estimated_length'], count=results['scored_length'], seconds=results['runtime']) }}</h4>
<ul>
	{% for result in results['list'] %}
	<li><a href="{{ url_for('document.view', space=result['space'], doc_id=result['id']) }}">{{ result['id'] }}</a> - {{ result['score'] }} - {{ result['rank'] }}</li>
	{% endfor %}
</ul>
{% endblock %}